// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-I1laHjoLoOMJecCuW4Ex_s8HPICSxQ',
    appId: '1:68200966561:web:d86346473fb9dffd33c3e0',
    messagingSenderId: '68200966561',
    projectId: 'flap-app-5c0c2',
    authDomain: 'flap-app-5c0c2.firebaseapp.com',
    storageBucket: 'flap-app-5c0c2.firebasestorage.app',
    measurementId: 'G-9NH9HR5NXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr0g16THsfy4wmSQ2HYVhOiOB3Jjh974I',
    appId: '1:68200966561:android:cc4c450b215bdbd033c3e0',
    messagingSenderId: '68200966561',
    projectId: 'flap-app-5c0c2',
    storageBucket: 'flap-app-5c0c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH8TYh6TRG3ugpysE3EgapvgUaFSDA7DY',
    appId: '1:68200966561:ios:49e22b61d0f2256d33c3e0',
    messagingSenderId: '68200966561',
    projectId: 'flap-app-5c0c2',
    storageBucket: 'flap-app-5c0c2.firebasestorage.app',
    iosBundleId: 'com.example.flapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH8TYh6TRG3ugpysE3EgapvgUaFSDA7DY',
    appId: '1:68200966561:ios:49e22b61d0f2256d33c3e0',
    messagingSenderId: '68200966561',
    projectId: 'flap-app-5c0c2',
    storageBucket: 'flap-app-5c0c2.firebasestorage.app',
    iosBundleId: 'com.example.flapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR-I1laHjoLoOMJecCuW4Ex_s8HPICSxQ',
    appId: '1:68200966561:web:ab8b2e98ead8b7a033c3e0',
    messagingSenderId: '68200966561',
    projectId: 'flap-app-5c0c2',
    authDomain: 'flap-app-5c0c2.firebaseapp.com',
    storageBucket: 'flap-app-5c0c2.firebasestorage.app',
    measurementId: 'G-VEDMN8EKKP',
  );
}
